import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { PropsWithChildren } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function HomeLayout({ children }: PropsWithChildren) {
  return (
    <div className="bg-primary w-full min-h-screen p-4">
      {children}
    </div>
  )
}