import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import MobileContainer from "@/components/MobileContainer"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="bg-primary w-full min-h-screen">
      {children}
    </div>
  )
}


{/* <div className="bg-primary w-full min-h-screen">
  {children}
</div> */}